import type DMMF from '@prisma/dmmf';

import { GeneratorConfig } from '../schemas';

export const DEFAULT_GENERATOR_CONFIG: GeneratorConfig = {
  useMultipleFiles: false,
  createInputTypes: true,
  createModelTypes: true,
  createOptionalDefaultValuesTypes: false,
  createRelationValuesTypes: false,
  createPartialTypes: false,
  addIncludeType: true,
  addSelectType: true,
  addInputTypeValidation: true,
  useDefaultValidators: true,
  prismaClientPath: '@prisma/client',
  coerceDate: true,
  writeNullishInModelTypes: false,
  isMongoDb: false,
  validateWhereUniqueInput: false,
  inputTypePath: 'inputTypeSchemas',
  outputTypePath: 'outputTypeSchemas',
  writeBarrelFiles: true,
  decimalJSInstalled: true,
  useTypeAssertions: false,
  useExactOptionalPropertyTypes: false,
  isPrismaClientGenerator: false,
  prismaLibraryPath: '@prisma/client/runtime/library',
  outputPath: './generated/zod',
  zodVersion: {
    major: 4,
    minor: 0,
    patch: 0,
  },
  prismaVersion: {
    major: 6,
    minor: 0,
    patch: 0,
  },
};

export const FIELD_BASE: DMMF.Field = {
  kind: 'scalar',
  name: 'test',
  isRequired: true,
  isList: false,
  isUnique: false,
  isId: false,
  isReadOnly: false,
  type: 'String',
  // dbNames: ['test'],
  isGenerated: false,
  isUpdatedAt: false,
  hasDefaultValue: false,
  default: undefined,
  relationToFields: undefined,
  relationOnDelete: undefined,
  relationName: undefined,
  documentation: undefined,
};
